version: "3.9"
services:
  yys_tool_react:
    restart: always
    container_name: yys_tool_react
    # custom image name here, just for build image yourself
    image: "yys_tool_react:dev"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - TZ=Asia/Shanghai
      - MODE=dev
    volumes:
      - ./:/app
  yys_tool_nginx:
    restart: always
    image: "nginx:1.23.3"
    ports:
      - "8889:80"
    volumes:
      - ./dist/:/usr/share/nginx/html/yys-tool-react
