version: '3.9'
services:
  yys_tool_react:
    # restart: always
    container_name: yys_tool_react
    image: 'node:20.12.2-slim'
    command: bash -c "npm install && npm run dev"
    working_dir: /var/local
    volumes:
      - ./:/var/local
    ports:
      - '8888:8888'
    environment:
      - TZ=Asia/Shanghai
  # yys_tool_nginx:
  #   restart: always
  #   image: "nginx:1.24.0"
  #   ports:
  #     - "8889:80"
  #   volumes:
  #     - ./dist/:/usr/share/nginx/html/yys-tool-react
