name: build yys-tool

on:
  push:
    branches: 
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: actions/setup-node@v1
        uses: actions/setup-node@v1
        with:
          node-version: '18.15.0'

      - name: npm_run_build
        run: |
          npm i && npm run build

      # 上传打包好的文件，所以下一步可以使用
      - name: upload files 
        uses: actions/upload-artifact@v2
        with: 
          name: build-dist
          path: dist
          retention-days: 1

  Deploy:
    needs: Build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write 
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: download build files
        uses: actions/download-artifact@v2
        with:
          name: build-dist
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: build-dist
          token: ${{ secrets.ACCESS_TOKEN }}
   